openapi: 3.0.1
info:
  title: Boilerplate 自定义接口文档
  version: 1.0.0
  description: "调用说明：\n1. 本文档仅包含数据模型默认开放的增删改查RESTful接口\n1. 接口请求/响应的Content-Type默认为application/json，UTF-8编码\n1. 如未额外说明，接口响应格式默认为以下JSON格式：\n\t- `code` - **业务状态码**，0表成功，非0表失败（错误码默认为-1，令牌失效为555），该值一定存在，请按照该值判断业务操作是否成功，`integer`\n\t- `msg` - **提示信息**，表正常或异常情况下的提示信息，有值才存在，`string`\n\t- `data` - **数据部分**，正常时返回请求数据，异常时返回错误详情，有值才存在，`类型视具体接口而定`\n1. 日期格式为`2019-06-04T02:42:01.472Z`，js代码：`new Date().toISOString()`\n1. 用户密码等信息统一为MD5加密后的32位小写字符串，npm推荐使用blueimp-md5\n"
paths:
  /book/private:
    post:
      summary: 查询私有图书信息
      description: |
        支持书名过滤
      operationId: bookPrivate
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
                  description: 订单id
                InStock:
                  type: boolean
                  description: 评价内容
      responses:
        default:
          description: 返回结果
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      tags:
        - Book
  /book/public:
    get:
      summary: 查询公共图书信息
      description: |
        支持图书分类过滤
      operationId: bookPublic
      parameters:
        - name: c
          in: query
          required: true
          schema:
            type: string
            enum:
              - 100
              - 200
              - 300
      responses:
        default:
          description: 返回结果
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      tags:
        - Book
tags:
  - name: Book
    description: 图书接口
servers:
  - url: 'https://example.com/api'
    description: 开发服务器
components:
  schemas:
    Book:
      type: object
      properties:
        Subject:
          type: string
          description: 书名
        Intro:
          type: string
          description: 简介
        Class:
          type: integer
          description: 分类
          enum:
            - 100
            - 200
            - 300
        Price:
          type: number
          description: 价格
        InStock:
          type: boolean
          description: 是否有货
        PubDate:
          type: string
          description: 出版日期
